### ISSUE TITLE
Enhance Selectors, Namespaces and Excludes

### ISSUE THREAD

**Issue by tarokkk** [kube-logging/fluent-plugin-label-router#2]
So there were several use-case that can be useful to the plugin users:

1. Multiple selector to allow `OR` statement

```
labels: HashMap {key => value}
```
We can use multiple selector to implement this:
```
<selector>
  labels: key:value
  namespace: default
</selector>
<selector>
  labels: key2:value2
</selector>
```
2. Extend namespace to list
With this enhancement we can add multiple namespaces for a match
```
<selector>
  labels: key2:value2
  namespaces: default,monitoring
</selector>
```
3. Inverse selectors "excludes"
This block will work as "anti" selectors that matches all records without these statements
```
<exclude>
  labels: key2:value2
  namespaces: default,monitoring
</exclude>
```
Full example:
```
<match example.tag**>
  @type label_router
  <route>
     <selector>
      namespace test,sandbox
      labels app:nginx
     </selector>
     <selector>
      namespace ingress
      labels app:nginx-ingress
     </selector>
     @label @NGINX
  </route>
</match>
```

**Comment by pepov** [comment]
looks great, random thoughts:
Is the exclude supposed to work together with selectors? (I think yes)
Is the order of the selectors/excludes matter? (I think no)

**Comment by tarokkk** [comment]
> looks great, random thoughts:
> Is the exclude supposed to work together with selectors? (I think yes)

Yes I think that's feasable
> Is the order of the selectors/excludes matter? (I think no)

No the whole section is evaluated like 1 expression

**Comment by tarokkk** [comment]
To grant evaluation order we changed  <selector> and <exclude> to <match> with negate: true option.
