### ISSUE TITLE
Not able to consume latest build changes of upgrading lib webrick from 1.8.1 to 1.8.2

### ISSUE THREAD

**Issue by devBmc** [kube-logging/fluent-plugin-label-router#25]
Commit : https://github.com/kube-logging/fluent-plugin-label-router/commit/848ddb45d9add46a81389ae06a435e4f60fafa3d
merged 
but when we consume the plugin using gem install it after merging the PR, it  still fetch gem.lock with older version of webrick.
Is anything needs to be done to consume the plugin with latest lib version updates??

**Comment by OverOrion** [comment]
Hey @devBmc 

The newest version 0.3.2 has been released, that should contain the newer lock file.
Let me know if it works for you.
