### ISSUE TITLE
Still having duplicate logs after the fix #7

### ISSUE THREAD

**Issue by xcompass** [kube-logging/fluent-plugin-label-router#9]
The same as #7. I was able to isolate the bug with the following config and this log ([test.log](https://github.com/banzaicloud/fluent-plugin-label-router/files/4378830/test.log))
```
<source>
  @type tail
  path /log/*.log
  pos_file /tmp/tail.pos
  tag kubernetes.*
  format json
  read_from_head true
</source>
<match **>
  @type label_router
  @id main_label_router
  <route>
    @label @d41d8cd98f00b204e9800998ecf8427e
    <match>
      namespaces
      negate false
    </match>
  </route>
</match>
<label @d41d8cd98f00b204e9800998ecf8427e>
  <match kubernetes.**>
    @type tag_normaliser
    @id es-flow_0_tag_normaliser
    format ${namespace_name}.${pod_name}.${container_name}
  </match>
  <match **>
    @type file
    @id logging_es-flow_local-output_file
    add_path_suffix true
    append true
    path /tmp/logs/${tag}/%Y%m%d.%H.%M
    <buffer tag,time>
      @type file
      path /buffers/logging_es-flow_local-output_file.*.buffer
      retry_forever true
      timekey 1m
      timekey_use_utc true
      timekey_wait 10s
    </buffer>
  </match>
</label>
```

Place the config in the current directory and log file in log/test.log and then run following command:
`docker run -it --rm --name fluentd -v ${PWD}/fluent.conf:/fluentd/etc/fluent.conf -v ${PWD}/log:/log banzaicloud/fluentd:v1.9.2-batch-fix fluentd`

Then check the duplicates
`docker exec -it fluentd cat /tmp/logs/unknown.unknown.unknown/19700101.00.33.log | sort | uniq -c | awk '{print $1}'`

The results should be all `1`. But at the end of results, there are a few 1030, which means some of the records are duplicated 1030 times.

I noticed that this duplication only happens after line 102x. If I reduce the number of lines below 1020, there is no duplication.

**Comment by tarokkk** [comment]
Thank you for the detailed example we will look into it!

**Comment by tarokkk** [comment]
Please check with the latest master as well. We tried your test and it worked fine!

**Comment by tarokkk** [comment]
As discussed on Slack it works as intended so far
